### ISSUE TITLE
Asking for password

### ISSUE THREAD

**Issue by yingtongbob** [proofgeist/mizu#5]
Open "proof_mizu_theme.fmp12" is asking to sign in. tried my credentials and also "Admin"

**Comment by ernestkoe** [comment]
huh, are you using the add-on?

**Comment by compmedtrics** [comment]
I heard about this theme at Engage 2024; I'm struggling to install it.  As previous post mentioned: Open "proof_mizu_theme.fmp12" is asking to sign in.   No credentials seem to work.  

Then I download the file "proof_mizu_theme.fmaddon" and try to open it and it cannot recognize the file-type. 

Not sure how to add this to FileMaker.

**Comment by ernestkoe** [comment]
Hey guys. Sorry for the delayed response. Can you tell me how you are getting to .fmp12 file? There should just be the addon.

**Comment by compmedtrics** [comment]
I eventually figured out how to add the addon to fileMaker and then add the addon to a file.
